id = "kanagawa-future-dim-theme"
name = "Kanagawa Future Dim"
version = "0.0.1"
schema_version = 1
authors = ["hame-ji"]
description = "A pale, soft, futuristic Kanagawa-inspired theme family for Zed."
repository = "https://github.com/hame-ji/zed-kanagawa-future-dim"
