id = "sumi-future-theme"
name = "Sumi Future"
version = "0.0.1"
schema_version = 1
authors = ["hame-ji"]
description = "A pale, soft, futuristic theme family for Zed."
repository = "https://github.com/hame-ji/zed-sumi-future-theme"
